version: "3"

services:
  
  shape_processor:
    build:
      context: ./
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_ACCESS_KEY_ID_SQS=x
      - AWS_SECRET_ACCESS_KEY_SQS=x
      - AWS_REGION_SQS=elasticmq
      - CUMULUS_MOCK_S3_UPLOAD=FALSE
      - CUMULUS_DBUSER=cumulus_user
      - CUMULUS_DBPASS=password
      - CUMULUS_DBNAME=postgres
      - CUMULUS_DBHOST=cumulusdb
      - QUEUE_NAME=cumulus-geoprocess
      - CUMULUS_API_URL=http://api:80
      - ENDPOINT_URL_SQS=http://elasticmq:9324
      - ENDPOINT_URL_S3=http://minio:9000
    volumes:
      - ./test_shapes:/test_shapes
      - ./app:/usr/src/app