version: "3"

networks:
  default:
    name: water-api_default

services:  
  shape_processor:
    build:
      context: ./
    environment:
      - APPLICATION_KEY=appkey
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_S3_ENDPOINT=minio:9000
      - AWS_ACCESS_KEY_ID_SQS=x
      - AWS_SECRET_ACCESS_KEY_SQS=x
      - AWS_REGION_SQS=elasticmq
      - QUEUE_NAME=water-geoprocess
      - WATER_API_URL=http://api
      - ENDPOINT_URL_SQS=http://elasticmq:9324
      - ENDPOINT_URL_S3=http://minio:9000
      - CPL_DEBUG=YES
      - CPL_CURL_VERBOSE=NO
      - AWS_VIRTUAL_HOSTING=FALSE
      - AWS_HTTPS=NO
    volumes:
      - ./app:/usr/src/app